spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  sql:
    init:
      mode: never

jwt:
  secret:
    key: ${jwt_secret_key}

cloud: # S3
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${s3_bucket_name}
    region:
      static: ap-northeast-2
    stack:
      auto: false


naver-cloud:
  access-key: ${ACCESS_KEY}
  secret-key: ${SECRET_KEY}
  service-id: ${SERVICE_ID}
  sender-phone: ${SENDER_PHONE}

